dev:
  mongo:
    host: localhost
    port: 27017
    dbname: dev_fullnode
  joola:
    host: "http://localhost:8080"
    apitoken: "apitoken-demo"
    collection: dev_bitcoin
  providers:
    list:
      - "Linode"
      - "DigitalOcean"
    linode:
      apikey: "LINODE-API-KEY"
      rootpass: "DESIRED-ROOT-PASSWORD"
      price: 2
    digitalocean:
      clientid: "DIGITALOCEAN-CLIENTID"
      apikey: "DIGITALOCEAN-API-KEY"
      price: 2
  general:
    runInterval: 20000
    callbackSecret: "CHANGE-THIS"
  coinbase:
    buttonid: "COINBASE-BUTTON-ID"
prod:
  mongo:
    host: localhost
    port: 27017
    dbname: prod_fullnode
  joola:
    host: "http://localhost:8080"
    apitoken: "apitoken-demo"
    collection: prod_bitcoin
  providers:
    list:
      - "Linode"
      - "DigitalOcean"
    linode:
      apikey: "LINODE-API-KEY"
      rootpass: "DESIRED-ROOT-PASSWORD"
      price: 3
    digitalocean:
      clientid: "DIGITALOCEAN-CLIENTID"
      apikey: "DIGITALOCEAN-API-KEY"
      price: 10
  general:
    runInterval: 20000
    callbackSecret: "CHANGE-THIS"
  coinbase:
    buttonid: "COINBASE-BUTTON-ID"