dev:
  mongo:
    host: localhost
    port: 27017
    dbname: dev_fullnode
  joola:
    host: "http://localhost:8080"
    apitoken: "apitoken-demo"
    collection: dev_bitcoin
  providers:
    linode:
      apikey: "LINODE-API-KEY"
      rootpass: "ROOT-PASSWORD"
      price: 3
  general:
    runInterval: 20000
    callbackSecret: "CHANGE-THIS"
  coinbase:
    buttonid: "1ec2d26bf6c385c40d2148253d5a4df2"
prod:
  mongo:
    host: localhost
    port: 27017
    dbname: fullnode
  joola:
    host: "http://localhost:8080"
    apitoken: "apitoken-demo"
    collection: bitcoin
  providers:
    linode:
      apikey: "LINODE-API-KEY"
      rootpass: "ROOT-PASSWORD"
      price: 20
  general:
    runInterval: 20000
    callbackSecret: "CHANGE-THIS"
  coinbase:
    buttonid: "1ec2d26bf6c385c40d2148253d5a4df2"